### ISSUE TITLE
made a similar plugin some time ago, discussing

### ISSUE THREAD

**Issue by michaelb** [jubnzv/mdeval.nvim#1]
Hi, I'm the main dev of [https://github.com/michaelb/sniprun](https://github.com/michaelb/sniprun).

It's not really an issue, more of a discussion (but discussion aren't enabled on your repo). Feel free to close at any time if not relevant or anything.

Just some context; Sniprun is a code-runner plugin that can execute code from the editor. It has several features such as various possible output; REPL-like mode for some languages, markdown-blocs support, auto-fetch of imports...

- What motivated you to make this plugin ?
- Did you search for any alternatives before starting your project, and if so, how ?
- Did you know about sniprun (I guess not but your never know) ?
- How do you think the two compare ?

**Comment by jubnzv** [comment]
Hi Michael,

Initially, I didn't plan to make a separate plugin. I was preparing to technical interviews and [my language of choice](https://en.wikipedia.org/wiki/C%2B%2B) was too tricky, so I decided to start writing some notes in markdown, which, of course, usually include some source code.

In the past, I was a big fan of Emacs's org-mode, and I remember the feature of evaluating code blocks inside org documents. It could be really useful to me, because I need to a way to have executable code blocks, like Jupiter notebooks, so that I can experiment with them and also make some notes in the same document.

So I created several functions in my Lua configuration file that implemented evaluation of code blocks. Then I saw that they could be separated as a plugin, and created this repository.

Answering your questions about Sniprun, I found it interesting. You've implemented much more functionality and already have some users.

I didn't know about it when started working on my plugin. But probably, I'll create my own plugin anyway, because I need a simple tool for a single use case described in the README, and I'm also not very familiar with Rust.

Anyway, I solved my task and I'm not planning to add more functionality to this plugin. So I won't compete with Sniprun in any way.

**Comment by michaelb** [comment]
>  So I won't compete with Sniprun in any way.

That wasn't a concern (nice 'competition' like this is fun anyway). I mostly wanted to inquire (without looking at the code for too long) whether there was some fundamental difference between our projects

The way you display the result is nice though, do you mind if I do something similar ?

**Comment by jubnzv** [comment]
Ah, well, of course I don't mind if you'll implement something similar. Moreover, you can use this code according to MIT license.

But I personally recommend you to take a look at [this section](https://orgmode.org/manual/Evaluating-Code-Blocks.html) of the documentation of org-mode first. This tool is fascinating, I believe you can get much more ideas there.

**Comment by michaelb** [comment]
Thanks! Have a good day

**Comment by jubnzv** [comment]
Good luck with your project :)
I also mentioned sniprun in README.

**Comment by michaelb** [comment]
Wow! Thanks!

I'll ping here if I decide to support Orgmode files one day :-)
